name: Tests/spec

on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup packages
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install -g pnpm
      - run: pnpm install

      - name: Run tests
        run: pnpm test
