services:
  egssite:
    image: ghcr.io/codingdiederik/egs-website:latest
    environment:
      - NODE_ENV=production
      - BACKEND_URL=${BACKEND_URL}
      - WP_USERNAME=${WP_USERNAME}
      - WP_PASSWORD=${WP_PASSWORD}
    ports:
      - "3000:3000"
    restart: unless-stopped